import { StyleSpecification } from "maplibre-gl";

export default {
    version: 8,
    name: "zbiorkom-openfreemap",
    metadata: {},
    center: [21.011956, 52.230009],
    zoom: 15.64,
    sources: {
        openfreemap: {
            type: "vector",
            url: "https://tiles.openfreemap.org/planet",
        },
    },
    sprite: "https://tiles.openfreemap.org/sprites/ofm_f384/ofm",
    glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
    layers: [
        {
            id: "background",
            type: "background",
            paint: {
                "background-color": "#e2e8f0",
            },
        },
        {
            id: "park",
            type: "fill",
            source: "openfreemap",
            "source-layer": "park",
            paint: {
                "fill-color": "#c3e6ce",
            },
        },
        {
            id: "landcover-wood",
            type: "fill",
            source: "openfreemap",
            "source-layer": "landcover",
            filter: ["==", "class", "wood"],
            paint: {
                "fill-color": "rgba(168, 214, 186, 0.8)",
            },
        },
        {
            id: "landcover-grass-scrub",
            type: "fill",
            source: "openfreemap",
            "source-layer": "landcover",
            filter: ["in", "class", "grass", "scrub"],
            paint: {
                "fill-color": "rgb(191, 227, 202)",
            },
        },
        {
            id: "landuse-wood",
            type: "fill",
            source: "openfreemap",
            "source-layer": "landuse",
            filter: ["==", "class", "wood"],
            paint: {
                "fill-color": "rgba(168, 214, 186, 0.8)",
            },
        },
        {
            id: "landuse-scrub",
            type: "fill",
            source: "openfreemap",
            "source-layer": "landuse",
            filter: ["==", "class", "scrub"],
            paint: {
                "fill-color": "rgba(197, 226, 206, 0.6)",
            },
        },
        {
            id: "landuse-agriculture-grass",
            type: "fill",
            source: "openfreemap",
            "source-layer": "landuse",
            filter: ["in", "class", "agriculture", "grass"],
            paint: {
                "fill-color": "rgba(217, 237, 223, 0.6)",
            },
        },
        {
            id: "landuse-cemetery",
            type: "fill",
            source: "openfreemap",
            "source-layer": "landuse",
            filter: ["==", "class", "cemetery"],
            paint: {
                "fill-color": "rgb(214, 237, 221)",
            },
        },
        {
            id: "landuse-pitch",
            type: "fill",
            source: "openfreemap",
            "source-layer": "landuse",
            filter: ["==", "class", "pitch"],
            paint: {
                "fill-color": "rgb(210, 240, 214)",
            },
        },
        {
            id: "waterway",
            type: "line",
            source: "openfreemap",
            "source-layer": "waterway",
            paint: {
                "line-color": "#d5e8f7",
                "line-width": [
                    "interpolate",
                    ["exponential", 1.3],
                    ["zoom"],
                    9,
                    ["match", ["get", "class"], ["canal", "river"], 0.1, 0],
                    20,
                    ["match", ["get", "class"], ["canal", "river"], 8, 3],
                ],
            },
        },
        {
            id: "water",
            type: "fill",
            source: "openfreemap",
            "source-layer": "water",
            paint: {
                "fill-color": "#d5e8f7",
            },
        },
        {
            id: "road-pedestrian-polygon-pattern",
            type: "fill",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "$type", "Polygon"],
                ["==", "class", "path"],
                ["in", "subclass", "footway", "platform"],
            ],
            paint: {
                "fill-opacity": ["interpolate", ["linear"], ["zoom"], 16, 0, 17, 1],
                "fill-color": "#f0f0f0",
            },
        },
        {
            id: "building",
            type: "fill",
            source: "openfreemap",
            "source-layer": "building",
            paint: {
                "fill-color": "#d3d7de",
                "fill-outline-color": "rgba(171, 183, 201, 0.8)",
            },
        },
        {
            id: "tunnel-steps",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["==", "subclass", "steps"]],
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 15, 1, 18, 4],
                "line-color": "rgb(166, 188, 216)",
                "line-opacity": 0.5,
                "line-dasharray": [0.3, 0.5],
            },
        },
        {
            id: "tunnel-path-pedestrian",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "brunnel", "tunnel"],
                ["in", "class", "path", "pedestrian"],
                ["!=", "subclass", "steps"],
            ],
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 15, 1, 18, 4],
                "line-color": "rgb(166, 188, 216)",
                "line-opacity": 0.7,
                "line-dasharray": [1, 0.5],
            },
        },
        {
            id: "tunnel-minor-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "track", "service", "minor"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 22, 4],
                "line-color": "rgb(220, 220, 220)",
                "line-gap-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 18, 15, 22, 150],
                "line-dasharray": [3, 3],
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-street-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "street", "street_limited"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 22, 4],
                "line-color": "rgb(220, 220, 220)",
                "line-gap-width": ["interpolate", ["exponential", 1.5], ["zoom"], 12, 0.5, 18, 20, 22, 200],
                "line-opacity": ["step", ["zoom"], 0, 14, 0.7],
                "line-dasharray": [3, 3],
            },
        },
        {
            id: "tunnel-secondary-tertiary-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "secondary", "tertiary"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 2, 22, 4],
                "line-color": "rgb(220, 220, 220)",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    0,
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 14.44, 26],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 144.4, 260],
                ],
                "line-dasharray": [3, 3],
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-primary-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["==", "class", "primary"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 2, 22, 4],
                "line-color": "rgb(220, 220, 220)",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 15.56, 28],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 155.6, 280],
                ],
                "line-dasharray": [3, 3],
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-motorway-trunk-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "motorway", "trunk"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 2, 22, 4],
                "line-color": "rgb(220, 220, 220)",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 16.67, 30],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 166.7, 300],
                ],
                "line-dasharray": [3, 3],
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-minor",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "track", "service", "minor"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 18, 15, 22, 150],
                "line-color": "#c2cbd6",
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-street",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "street", "street_limited"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 12, 0.5, 18, 20, 22, 200],
                "line-color": "#c2cbd6",
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-secondary-tertiary",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "secondary", "tertiary"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    0,
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 14.44, 26],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 144.4, 260],
                ],
                "line-color": "#c2cbd6",
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-primary",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["==", "class", "primary"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 15.56, 28],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 155.6, 280],
                ],
                "line-color": "#f0ce8e",
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-motorway-trunk",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["in", "class", "motorway", "trunk"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 16.67, 30],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 166.7, 300],
                ],
                "line-color": [
                    "match",
                    ["get", "class"],
                    "motorway",
                    "rgb(255, 190, 135)",
                    "rgb(242, 223, 148)",
                ],
                "line-opacity": 0.7,
            },
        },
        {
            id: "tunnel-rail",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "brunnel", "tunnel"],
                ["in", "subclass", "rail", "subway", "light_rail", "narrow_gauge"],
            ],
            paint: {
                "line-color": "#7b92b2",
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14, 0.6, 20, 3],
                "line-opacity": 0.5,
            },
        },
        {
            id: "tunnel-rail-hatching",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "brunnel", "tunnel"],
                ["in", "subclass", "rail", "subway", "light_rail", "narrow_gauge"],
            ],
            paint: {
                "line-color": "#7b92b2",
                "line-dasharray": [0.2, 8],
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14.5, 0, 20, 8],
                "line-opacity": 0.5,
            },
        },
        {
            id: "tunnel-tram",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "tunnel"], ["==", "subclass", "tram"]],
            paint: {
                "line-color": "#a3a9b4",
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14, 0.6, 20, 1.5],
                "line-opacity": 0.5,
            },
        },
        {
            id: "road-minor-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["!in", "brunnel", "bridge", "tunnel"],
                ["in", "class", "track", "service", "minor"],
            ],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.2, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 18, 15, 22, 150],
            },
        },
        {
            id: "road-street-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["in", "class", "street", "street_limited"],
                ["!in", "brunnel", "bridge", "tunnel"],
            ],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.2, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": ["interpolate", ["exponential", 1.5], ["zoom"], 12, 0.5, 18, 20, 22, 200],
                "line-opacity": ["step", ["zoom"], 0, 14, 1],
            },
        },
        {
            id: "road-secondary-tertiary-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["in", "class", "secondary", "tertiary"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.2, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    0,
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 14.44, 26],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 144.4, 260],
                ],
            },
        },
        {
            id: "road-primary-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "class", "primary"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 15.56, 28],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 155.6, 280],
                ],
            },
        },
        {
            id: "road-motorway-trunk-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["in", "class", "motorway", "trunk"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 22, 4],
                "line-color": "rgb(255, 255, 255)",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 16.67, 30],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 166.7, 300],
                ],
                "line-opacity": ["interpolate", ["linear"], ["zoom"], 3, 0, 3.5, 1],
            },
        },
        {
            id: "road-steps",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "subclass", "steps"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 15, 1, 18, 6],
                "line-color": "#a6bcd8",
                "line-dasharray": [0.3, 0.5],
            },
        },
        {
            id: "chodniki",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "$type", "LineString"],
                ["in", "class", "path", "footway", "pedestrian"],
                ["!in", "subclass", "cycleway", "steps"],
                ["!in", "brunnel", "bridge", "tunnel"],
            ],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 0.5, 18, 4],
                "line-color": "#a6bcd8",
                "line-dasharray": [1, 0.25],
            },
        },
        {
            id: "sciezki rowerowe",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "subclass", "cycleway"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 0.5, 18, 4],
                "line-color": "#8cab98",
                "line-dasharray": [1, 0.25],
            },
        },
        {
            id: "road-minor",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["in", "class", "track", "service", "minor"],
                ["!=", "ramp", 1],
                ["!in", "brunnel", "bridge", "tunnel"],
            ],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 18, 15, 22, 150],
                "line-color": "#c2cbd6",
            },
        },
        {
            id: "road-street",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["in", "class", "street", "street_limited"],
                ["!=", "ramp", 1],
                ["!in", "brunnel", "bridge", "tunnel"],
            ],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 12, 0.5, 18, 20, 22, 200],
                "line-color": "#c2cbd6",
                "line-opacity": ["step", ["zoom"], 0, 14, 1],
            },
        },
        {
            id: "road-secondary-tertiary",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["in", "class", "secondary", "tertiary"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    0,
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 14.44, 26],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 144.4, 260],
                ],
                "line-color": "#c2cbd6",
            },
        },
        {
            id: "road-primary",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "class", "primary"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 15.56, 28],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 155.6, 280],
                ],
                "line-color": "#f5bd5e",
            },
        },
        {
            id: "road-motorway-trunk",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["in", "class", "motorway", "trunk"], ["!in", "brunnel", "bridge", "tunnel"]],
            layout: {
                "line-cap": "round",
                "line-join": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 16.67, 30],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 166.7, 300],
                ],
                "line-color": [
                    "step",
                    ["zoom"],
                    [
                        "match",
                        ["get", "class"],
                        "motorway",
                        "rgb(242, 148, 66)",
                        "trunk",
                        "rgb(230, 189, 28)",
                        "rgb(255, 255, 255)",
                    ],
                    9,
                    ["match", ["get", "class"], "motorway", "rgb(255, 163, 84)", "rgb(244, 214, 95)"],
                ],
                "line-opacity": ["interpolate", ["linear"], ["zoom"], 3, 0, 3.5, 1],
            },
        },
        {
            id: "road-rail",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["!in", "brunnel", "bridge", "tunnel"],
                ["in", "subclass", "rail", "subway", "light_rail", "narrow_gauge"],
            ],
            paint: {
                "line-color": "#7b92b2",
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14, 0.6, 20, 3],
            },
        },
        {
            id: "road-rail-hatching",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["!in", "brunnel", "bridge", "tunnel"],
                ["in", "subclass", "rail", "subway", "light_rail", "narrow_gauge"],
            ],
            paint: {
                "line-color": "#7b92b2",
                "line-dasharray": [0.2, 8],
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14.5, 0, 20, 8],
            },
        },
        {
            id: "road-tram",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["!in", "brunnel", "bridge", "tunnel"], ["==", "subclass", "tram"]],
            paint: {
                "line-color": "#a3a9b4",
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14, 0.5, 20, 1],
            },
        },
        {
            id: "bridge-minor-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "track", "service", "minor"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.2, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1, 18, 10, 22, 100],
            },
        },
        {
            id: "bridge-street-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "street", "street_limited"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.2, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": ["interpolate", ["exponential", 1.5], ["zoom"], 12, 0.5, 18, 20, 22, 200],
                "line-opacity": ["step", ["zoom"], 0, 14, 1],
            },
        },
        {
            id: "bridge-steps-casing",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["==", "subclass", "steps"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 15, 2, 18, 8],
                "line-color": "#dfe3e8",
            },
        },
        {
            id: "bridge-chodniki-casing",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "brunnel", "bridge"],
                ["in", "class", "path", "footway", "pedestrian"],
                ["!in", "subclass", "cycleway", "steps"],
            ],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 1.5, 18, 6],
                "line-color": "#dfe3e8",
            },
        },
        {
            id: "bridge-sciezki-rowerowe-casing",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["==", "subclass", "cycleway"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 1.5, 18, 6],
                "line-color": "#dfe3e8",
            },
        },
        {
            id: "bridge-secondary-tertiary-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "secondary", "tertiary"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1.5, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    0,
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 14.44, 26],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 144.4, 260],
                ],
                "line-opacity": ["step", ["zoom"], 0, 10, 1],
            },
        },
        {
            id: "bridge-primary-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["==", "class", "primary"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 2, 22, 4],
                "line-color": "#dfe3e8",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 15.56, 28],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 155.6, 280],
                ],
                "line-opacity": ["step", ["zoom"], 0, 10, 1],
            },
        },
        {
            id: "bridge-motorway-trunk-case",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "motorway", "trunk"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 2, 22, 4],
                "line-color": "rgb(255, 255, 255)",
                "line-gap-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 16.67, 30],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 166.7, 300],
                ],
            },
        },
        {
            id: "bridge-minor",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "track", "service", "minor"]],
            layout: {
                "line-cap": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 14, 1, 18, 10, 22, 100],
                "line-color": "#c2cbd6",
            },
        },
        {
            id: "bridge-street",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "street", "street_limited"]],
            layout: {
                "line-cap": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 12, 0.5, 18, 20, 22, 200],
                "line-color": "#c2cbd6",
                "line-opacity": ["step", ["zoom"], 0, 14, 1],
            },
        },
        {
            id: "bridge-steps",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["==", "subclass", "steps"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 15, 1, 18, 6],
                "line-color": "#a6bcd8",
                "line-dasharray": [0.3, 0.5],
            },
        },
        {
            id: "bridge-chodniki",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "$type", "LineString"],
                ["==", "brunnel", "bridge"],
                ["in", "class", "path", "footway", "pedestrian"],
                ["!in", "subclass", "cycleway", "steps"],
            ],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 0.5, 18, 4],
                "line-color": "#a6bcd8",
                "line-dasharray": [1, 0.25],
            },
        },
        {
            id: "bridge-sciezki-rowerowe",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["==", "subclass", "cycleway"]],
            layout: {
                "line-join": "round",
            },
            paint: {
                "line-width": ["interpolate", ["exponential", 1.5], ["zoom"], 13, 0.5, 18, 4],
                "line-color": "#8cab98",
                "line-dasharray": [1, 0.25],
            },
        },
        {
            id: "bridge-secondary-tertiary",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "secondary", "tertiary"]],
            layout: {
                "line-cap": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    0,
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 14.44, 26],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 144.4, 260],
                ],
                "line-color": "#c2cbd6",
            },
        },
        {
            id: "bridge-primary",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["==", "class", "primary"]],
            layout: {
                "line-cap": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 15.56, 28],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 155.6, 280],
                ],
                "line-color": "#f5bd5e",
            },
        },
        {
            id: "bridge-motorway-trunk",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["in", "class", "motorway", "trunk"]],
            layout: {
                "line-cap": "round",
            },
            paint: {
                "line-width": [
                    "interpolate",
                    ["exponential", 1.5],
                    ["zoom"],
                    3,
                    ["case", ["==", ["get", "ramp"], 1], 0.44, 0.8],
                    18,
                    ["case", ["==", ["get", "ramp"], 1], 16.67, 30],
                    22,
                    ["case", ["==", ["get", "ramp"], 1], 166.7, 300],
                ],
                "line-color": [
                    "match",
                    ["get", "class"],
                    "motorway",
                    "rgb(255, 163, 84)",
                    "rgb(244, 214, 95)",
                ],
            },
        },
        {
            id: "bridge-rail",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "brunnel", "bridge"],
                ["in", "subclass", "rail", "subway", "light_rail", "narrow_gauge"],
            ],
            paint: {
                "line-color": "#7b92b2",
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14, 0.6, 20, 3],
            },
        },
        {
            id: "bridge-rail-hatching",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: [
                "all",
                ["==", "brunnel", "bridge"],
                ["in", "subclass", "rail", "subway", "light_rail", "narrow_gauge"],
            ],
            paint: {
                "line-color": "#7b92b2",
                "line-dasharray": [0.2, 8],
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14.5, 0, 20, 8],
            },
        },
        {
            id: "bridge-tram",
            type: "line",
            source: "openfreemap",
            "source-layer": "transportation",
            filter: ["all", ["==", "brunnel", "bridge"], ["==", "subclass", "tram"]],
            paint: {
                "line-color": "#a3a9b4",
                "line-width": ["interpolate", ["exponential", 1.4], ["zoom"], 14, 0.5, 20, 1],
            },
        },
        {
            id: "admin-1-boundary",
            type: "line",
            source: "openfreemap",
            "source-layer": "boundary",
            filter: ["all", ["==", "admin_level", 1], ["==", "maritime", 0]],
            paint: {
                "line-dasharray": [2, 2],
                "line-width": ["interpolate", ["linear"], ["zoom"], 3, 0.3, 12, 1.5],
                "line-opacity": ["interpolate", ["linear"], ["zoom"], 2, 0, 3, 1],
                "line-color": "rgb(190, 197, 204)",
            },
        },
        {
            id: "admin-0-boundary",
            type: "line",
            source: "openfreemap",
            "source-layer": "boundary",
            filter: ["all", ["==", "admin_level", 0], ["==", "disputed", 0], ["==", "maritime", 0]],
            paint: {
                "line-color": "#b0b8c1",
                "line-width": ["interpolate", ["linear"], ["zoom"], 3, 0.5, 12, 2],
                "line-dasharray": [10, 0],
            },
        },
        {
            id: "admin-0-boundary-disputed",
            type: "line",
            source: "openfreemap",
            "source-layer": "boundary",
            filter: ["all", ["==", "disputed", 1], ["==", "admin_level", 0], ["==", "maritime", 0]],
            paint: {
                "line-color": "#b0b8c1",
                "line-width": ["interpolate", ["linear"], ["zoom"], 3, 0.5, 12, 2],
                "line-dasharray": [2, 1.5],
            },
        },
        {
            id: "building-number-label",
            type: "symbol",
            source: "openfreemap",
            "source-layer": "housenumber",
            minzoom: 16,
            layout: {
                "text-field": ["get", "housenumber"],
                "text-font": ["Noto Sans Regular"],
                "text-padding": 4,
                "text-max-width": 7,
                "text-size": 10,
            },
            paint: {
                "text-color": "rgb(110, 130, 162)",
                "text-halo-color": "rgb(232, 236, 240)",
                "text-halo-width": 1,
            },
        },
        {
            id: "road-label",
            type: "symbol",
            source: "openfreemap",
            "source-layer": "transportation_name",
            filter: ["has", "name"],
            layout: {
                "text-size": [
                    "interpolate",
                    ["linear"],
                    ["zoom"],
                    10,
                    [
                        "match",
                        ["get", "class"],
                        ["motorway", "trunk", "primary", "secondary", "tertiary"],
                        10,
                        9,
                    ],
                    18,
                    [
                        "match",
                        ["get", "class"],
                        ["motorway", "trunk", "primary", "secondary", "tertiary"],
                        16,
                        14,
                    ],
                ],
                "text-max-angle": 30,
                "text-font": ["Noto Sans Regular"],
                "symbol-placement": "line",
                "text-padding": 5,
                "text-rotation-alignment": "map",
                "text-pitch-alignment": "viewport",
                "text-field": ["get", "name"],
                "text-letter-spacing": 0.01,
            },
            paint: {
                "text-color": "#7f8691",
                "text-halo-color": [
                    "match",
                    ["get", "class"],
                    ["motorway", "trunk"],
                    "rgba(255, 255, 255, 0.75)",
                    "rgb(255, 255, 255)",
                ],
                "text-halo-width": 1,
                "text-halo-blur": 1,
            },
        },
        {
            id: "settlement-subdivision-label",
            type: "symbol",
            source: "openfreemap",
            "source-layer": "place",
            filter: ["==", "class", "suburb"],
            layout: {
                "text-field": ["get", "name"],
                "text-transform": "uppercase",
                "text-font": ["Noto Sans Regular"],
                "text-letter-spacing": 0.15,
                "text-max-width": 7,
                "text-padding": 3,
                "text-size": ["interpolate", ["cubic-bezier", 0.5, 0, 1, 1], ["zoom"], 11, 11, 15, 15],
            },
            paint: {
                "text-halo-color": "rgba(255, 255, 255, 0.75)",
                "text-halo-width": 1,
                "text-color": "rgb(105, 117, 131)",
                "text-halo-blur": 0.5,
            },
        },
        {
            id: "settlement-minor-label",
            type: "symbol",
            source: "openfreemap",
            "source-layer": "place",
            filter: ["in", "class", "hamlet", "village", "town"],
            layout: {
                "text-line-height": 1.1,
                "text-size": [
                    "interpolate",
                    ["cubic-bezier", 0.2, 0, 0.9, 1],
                    ["zoom"],
                    3,
                    8,
                    6,
                    10,
                    8,
                    11,
                    13,
                    14,
                ],
                "text-font": ["Noto Sans Regular"],
                "text-justify": "auto",
                "text-anchor": "center",
                "text-field": ["get", "name"],
                "text-max-width": 7,
            },
            paint: {
                "text-color": "rgb(24, 27, 30)",
                "text-halo-color": "rgb(255, 255, 255)",
                "text-halo-width": 1,
                "text-halo-blur": 1,
            },
        },
        {
            id: "settlement-major-label",
            type: "symbol",
            source: "openfreemap",
            "source-layer": "place",
            filter: [
                "all",
                ["==", "class", "city"],
                [
                    "in",
                    "name",
                    "Warszawa",
                    "Kraków",
                    "Łódź",
                    "Wrocław",
                    "Poznań",
                    "Gdańsk",
                    "Szczecin",
                    "Bydgoszcz",
                    "Lublin",
                    "Białystok",
                    "Katowice",
                    "Gdynia",
                    "Częstochowa",
                    "Radom",
                    "Toruń",
                    "Kielce",
                    "Rzeszów",
                    "Olsztyn",
                    "Zielona Góra",
                    "Gorzów Wielkopolski",
                    "Opole",
                ],
            ],
            layout: {
                "text-line-height": 1.1,
                "text-size": [
                    "interpolate",
                    ["cubic-bezier", 0.2, 0, 0.9, 1],
                    ["zoom"],
                    3,
                    13,
                    6,
                    18,
                    8,
                    20,
                    15,
                    24,
                ],
                "text-font": ["Noto Sans Regular"],
                "text-justify": "center",
                "text-anchor": "center",
                "text-field": ["get", "name"],
                "text-max-width": 7,
            },
            paint: {
                "text-color": "rgb(24, 27, 30)",
                "text-halo-color": "rgb(255, 255, 255)",
                "text-halo-width": 1,
                "text-halo-blur": 1,
            },
        },
        {
            id: "country-label",
            type: "symbol",
            source: "openfreemap",
            "source-layer": "place",
            filter: ["==", "class", "country"],
            layout: {
                "text-field": ["get", "name"],
                "text-line-height": 1.1,
                "text-max-width": 6,
                "text-font": ["Noto Sans Regular"],
                "text-justify": "auto",
                "text-size": ["interpolate", ["cubic-bezier", 0.2, 0, 0.7, 1], ["zoom"], 1, 11, 9, 22],
            },
            paint: {
                "text-color": "rgb(24, 27, 30)",
                "text-halo-color": [
                    "interpolate",
                    ["linear"],
                    ["zoom"],
                    2,
                    "rgba(255, 255, 255, 0.75)",
                    3,
                    "rgb(255, 255, 255)",
                ],
                "text-halo-width": 1.25,
            },
        },
    ],
} as StyleSpecification;
